import sys 
sys.path.append("../build/Release/")
import mytorch
import torch, numpy as np, unittest


class TestBatchNorm(unittest.TestCase):
    def test_forward(self):
        mytorch.set_default_device(mytorch.Cpu)
        a = np.random.rand(2 , 6 , 8 , 8).astype(np.float32)
        mytorch_a = mytorch.tensor_from_numpy(a)
        torch_a = torch.from_numpy(a)
        mytorch_conv = mytorch.nn.Conv2d(6 , 6 , 5)
        torch_conv = torch.nn.Conv2d(6 , 6 , 5)
        torch_conv.weight = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[0])))
        torch_conv.bias = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[1])))
        mytorch_bn = mytorch.nn.BatchNorm2d(6)
        torch_bn = torch.nn.BatchNorm2d(6)
        mytorch_conv_out = mytorch_conv(mytorch_a)
        mytorch_out = mytorch_bn(mytorch_conv_out)
        torch_conv_out = torch_conv(torch_a)
        torch_out = torch_bn(torch_conv_out)
        self.assertTrue(np.allclose(mytorch.numpy_from_tensor(mytorch_out), torch_out.cpu().detach().numpy(),atol = 1e-4))
    def test_backward(self):
        mytorch.set_default_device(mytorch.Cpu)
        a = np.random.rand(2 , 6 , 8 , 8).astype(np.float32)
        grad_upstream = np.random.rand(2 , 6 , 4 , 4).astype(np.float32)
        mytorch_grad_upstream = mytorch.tensor_from_numpy(grad_upstream)
        mytorch_a = mytorch.tensor_from_numpy(a)
        mytorch_a.set_requires_grad(True)
        torch_a = torch.from_numpy(a)
        torch_a.requires_grad = True
        mytorch_bn = mytorch.nn.BatchNorm2d(6)
        torch_bn = torch.nn.BatchNorm2d(6)
        mytorch_conv = mytorch.nn.Conv2d(6 , 6 , 5)
        torch_conv = torch.nn.Conv2d(6 , 6 , 5)
        torch_conv.weight = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[0])))
        torch_conv.bias = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[1])))
        mytorch_out = mytorch_bn(mytorch_conv(mytorch_a))
        torch_out = torch_bn(torch_conv(torch_a))
        mytorch_out.zero_grad()
        mytorch_out.backward(mytorch_grad_upstream)
        torch_grad_upstream = torch.from_numpy(grad_upstream)
        torch_out.backward(torch_grad_upstream)
        self.assertTrue(np.allclose(mytorch.numpy_from_tensor(mytorch_a.get_grad_tensor()), torch_a.grad.cpu().numpy(),atol = 1e-3) )

    def test_forward_cuda(self):
        mytorch.set_default_device(mytorch.Cuda)
        a = np.random.rand(2 , 6 , 8 , 8).astype(np.float32)
        mytorch_a = mytorch.tensor_from_numpy(a)
        torch_a = torch.from_numpy(a)
        mytorch_conv = mytorch.nn.Conv2d(6 , 6 , 5)
        torch_conv = torch.nn.Conv2d(6 , 6 , 5)
        torch_conv.weight = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[0])))
        torch_conv.bias = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[1])))
        mytorch_bn = mytorch.nn.BatchNorm2d(6)
        torch_bn = torch.nn.BatchNorm2d(6)
        mytorch_conv_out = mytorch_conv(mytorch_a)
        mytorch_out = mytorch_bn(mytorch_conv_out)
        torch_conv_out = torch_conv(torch_a)
        torch_out = torch_bn(torch_conv_out)
        self.assertTrue(np.allclose(mytorch.numpy_from_tensor(mytorch_out), torch_out.cpu().detach().numpy(),atol = 1e-5))
    def test_backward_cuda(self):
        mytorch.set_default_device(mytorch.Cuda)
        a = np.random.rand(2 , 6 , 8 , 8).astype(np.float32)
        grad_upstream = np.random.rand(2 , 6 , 4 , 4).astype(np.float32)
        mytorch_grad_upstream = mytorch.tensor_from_numpy(grad_upstream)
        mytorch_a = mytorch.tensor_from_numpy(a)
        mytorch_a.set_requires_grad(True)
        torch_a = torch.from_numpy(a)
        torch_a.requires_grad = True
        mytorch_bn = mytorch.nn.BatchNorm2d(6)
        torch_bn = torch.nn.BatchNorm2d(6)
        mytorch_conv = mytorch.nn.Conv2d(6 , 6 , 5)
        torch_conv = torch.nn.Conv2d(6 , 6 , 5)
        torch_conv.weight = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[0])))
        torch_conv.bias = torch.nn.Parameter(torch.from_numpy(mytorch.numpy_from_tensor(mytorch_conv.parameters()[1])))
        mytorch_out = mytorch_bn(mytorch_conv(mytorch_a))
        torch_out = torch_bn(torch_conv(torch_a))
        mytorch_out.zero_grad()
        mytorch_out.backward(mytorch_grad_upstream)
        torch_grad_upstream = torch.from_numpy(grad_upstream)
        torch_out.backward(torch_grad_upstream)
        self.assertTrue(np.allclose(mytorch.numpy_from_tensor(mytorch_a.get_grad_tensor()), torch_a.grad.cpu().numpy(),atol = 1e-5) )



if __name__ == "__main__":
    mytorch.set_default_device(mytorch.Cuda)
    unittest.main()